CREATE TABLE site_tag_to_id_lookup (
  LOGICAL_SHARD_ID int(11) NOT NULL,
	LOOKUP_KEY VARCHAR(100) NOT NULL,
	LOOKUP_VALUE BIGINT NOT NULL,
	PRIMARY KEY (LOOKUP_VALUE),
	INDEX LOOKUP_KEY (LOOKUP_KEY)
) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE user_email_to_id_lookup (
  LOGICAL_SHARD_ID int(11) NOT NULL,
	LOOKUP_KEY VARCHAR(100) NOT NULL,
	LOOKUP_VALUE BIGINT NOT NULL,
	PRIMARY KEY (LOOKUP_VALUE),
	INDEX LOOKUP_KEY (LOOKUP_KEY)
) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_bin;
