CREATE TABLE article (
  LOGICAL_SHARD_ID int(11) DEFAULT NULL,
	ARTICLE_ID BIGINT NOT NULL,
	VERSION BIGINT NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	CREATE_BY VARCHAR(50) NOT NULL,
	PRIMARY KEY (ARTICLE_ID, VERSION)
) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_bin;

