CREATE TABLE article (
  LOGICAL_SHARD_ID int(11) NOT NULL,
	ARTICLE_ID BIGINT NOT NULL,
	SITE_ID BIGINT NOT NULL,
	VERSION int(11) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT TEXT NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	MODIFIED_BY VARCHAR(50) NOT NULL,
	MODIFIED_DATE DATETIME NOT NULL,
	PRIMARY KEY (ARTICLE_ID, VERSION),
	INDEX SITE_CREATE_DATE_ARTICLE_ID_VERSION (SITE_ID, CREATE_DATE, ARTICLE_ID, VERSION)
) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_bin;

