CREATE TABLE IF NOT EXISTS `user` (
  `USER_ID` bigint(20) NOT NULL,
  `EMAIL` varchar(100) COLLATE utf8_general_ci NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `MOBILE` varchar(20) DEFAULT NULL,
  `COUNTRY` varchar(2) DEFAULT NULL,
  `BIRTHDAY` date DEFAULT NULL,
  `CREATE_DATE` date DEFAULT NULL,
  `MODIFIED_DATE` date DEFAULT NULL,
  `MODIFIED_BY` varchar(20) DEFAULT NULL,
  `LOGICAL_SHARD_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `EMAIL` (`EMAIL` ASC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
